- name: Stooges
  webhook: https://4f9gs2dqw3.execute-api.us-east-1.amazonaws.com/prod/
  language: nodejs
- name: Glitch
  webhook: https://8ballagent.glitch.me
  language: nodejs
- name: PHPBall
  webhook: https://billw.dev
  language: php
- name: AlwaysYes
  webhook: https://raw.githubusercontent.com/qccoders/8ball/jp/static-agent/agents/static/jp/
  language: json
- name: Kucksdorfs
  webhook: http://8ball.kucksdorfs.com/
  language: cs
- name: FSharp
  webhook: http://whatnet.us:5000
  language: f#
- name: Python+Flask
  webhook: http://whatnet.us:5001
  language: python
- name: Ruby+Sinatra
  webhook: http://whatnet.us:5002
  language: ruby
- name: Elixir+Phoenix
  webhook: http://whatnet.us:5003/api
  language: elixir
- name: Go(lang)
  webhook: http://whatnet.us:5004
  language: go