workflows:
  version: 2
  main:
    jobs:
      - build:
          filters:
            branches:
              only: master

version: 2
jobs:
  build:
    docker:
      - image: docker
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: ./build/build.sh
      - run: ./build/deploy.sh