version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:latest
    steps:
      - checkout
      - run: 
          name: Instal Node
          command: sudo apt-get install nodejs
      - run: 
          name: Install NPM
          command: sudo apt-get install npm
      - run: 
          name: Install Yarn
          command: sudo npm install -g yarn
      - setup_remote_docker:
          docker_layer_caching: true
      - run: 
          name: Build
          command: bash ./build/build.sh
      - run:
          name: Deploy (master only)
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              bash ./build/deploy.sh
            fi