workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:latest
    steps:
      - checkout
      - run: apt-get install nodejs
      - run: apt-get install npm
      - run: npm install -g yarn
      - setup_remote_docker:
          docker_layer_caching: true
      - run: bash ./build/build.sh
  deploy:
    docker:
      - image: circleci/golang:latest
    steps:
      - run:
          name: Deploy
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              bash ./build/deploy.sh
            fi